# Server
server.port=8080
spring.application.name=salary-slip-system

# MongoDB
spring.data.mongodb.uri=
spring.data.mongodb.database=salaryslip

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



Mail (Gmail SMTP) — replace with your credentials
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Company name shown on salary slips
app.company.name=akk Pvt Ltd
app.company.email=