# Server
server.port=${PORT:8080}
spring.application.name=salary-slip-system

# MongoDB — Render environment variable se aayega
spring.data.mongodb.uri=mongodb+srv://meerayadav993961_db_user:g9sNB9gfMDL%23Tm_@cluster0.3lgmfpp.mongodb.net/salaryslip?retryWrites=true&w=majority
spring.data.mongodb.database=salaryslip

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Mail (Gmail SMTP) — Render environment variable se aayega
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=userakashinfo@gmail.com
spring.mail.password=njdnlthhevlgovdy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Company name
app.company.name=akyd_21
app.company.email=userakashinfo@gmail.com